### ISSUE TITLE
Failed to get queue length for queue

### ISSUE THREAD

**Issue by vdoodala** [mbogus/docker-kube-amqp-autoscale#3]
I am getting following error - 

Failed to get queue length for queue example: parse 'amqp://username:password@hostname:5672//': first path segment in URL cannot contain colon

How to resolve the issue?? Any inputs ???

**Comment by raphaelottevaere** [comment]
In GO 1.10.1 the manner in which request are send changed. Revert back to an older version of GO to circumvent the issues. 
The GO 1.8.3 version is working for me atm.

**Comment by Skyel14** [comment]
Hi, how do we do this revert in the provided Dockerfile? I think the current latest Dockerfile is broken by this issue,

**Comment by mbogus** [comment]
Latest build should handle quoted RabbitMQ URIs
